---
title: "Kernel Smoothing"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r eruptions, echo=FALSE}
library(shiny)
library(ggplot2)

# PDE
gauss.kernel = function(x, y,ind,b,win,proportion){
  b = max(b, 1e-6)
  ran = (max(range(x)) - min(range(x)))*proportion
  
  xfix = x[ind]
  
  ub =  min(xfix + win*b, xfix + ran/2) #upperbound
  lb =  max(xfix - win*b, xfix - ran/2) #lowerbound
  
  xnew = x[x >= lb & x <= ub]
  ynew = y[x >= lb & x <= ub]
  k = exp(-((xfix - xnew)^2)/(2*b))
  yhat = sum(k*ynew)/sum(k)
  return(yhat)
}

gaussian.smooth = function(x,y,b,win,proportion){
  yhat = vector(length = length(y))
  for(i in 1:length(y)){
    yhat[i] = gauss.kernel(x,y,i,b[i],win,proportion)  # adaptive bandwidth
  }
  return(yhat)
}



###################################################################

# Shinny

ui <- fluidPage(
  
  # Application title
  #titlePanel("Kernel Smoother"),
  
  # Sidebar with a slider input for number of bins 
  fluidRow(
    column(4, 
           textInput(inputId = "seed",
                     label = "Choose set.seed",
                     value = "1"),
           
           textInput(inputId = "equation", 
                     label = "Underlying function", 
                     value = "x^4"),
           
           textInput(inputId = "u2", 
                     label = "Second Derivative of Underlying function", 
                     value = "12*x^2")
    ),
    column(4,
           sliderInput(inputId = "nobs",
                       label = "Number of observations",
                       min = 2,
                       max = 300,
                       value = 200),
           
           sliderInput("xrange",
                       "Range of x:",
                       min = -10,
                       max = 10,
                       value = c(-5,5) ),
           
           textInput(inputId = "sdtext", 
                     label = "Standard deviation of noise",
                     value = "100")
    ),
    column(4, 
           sliderInput(inputId = "win",
                       label = "Set Window",
                       min = 0,
                       max = 20,
                       value = 5),
           
           sliderInput(inputId = "proportion",
                       label = "Set Proportion of Range",
                       min = 1,
                       max = 10,
                       value = 5),
           
           sliderInput(inputId = "sim",
                       label = "Simulation Number",
                       min = 100,
                       max = 1000,
                       value = 100)
    )
  ),
  
  fluidRow(
    column(6, 
           plotOutput("Plot1")),
    column(6, 
           plotOutput("Plot2"))
  )
)








###################################################################


server <- function(input, output){
  
  equation = function(x){ eval(parse(text = input$equation)) }
  u2 = function(x){ eval(parse(text = input$u2)) }
  
  sdtext = function(x){ eval(parse(text = input$sdtext)) }
  
  xvalue = reactive({ seq(input$xrange[1], input$xrange[2], length.out = input$nobs) })
  
  noise = reactive({
    set.seed(input$seed)
    rnorm(input$nobs, mean = 0, sd = sdtext(xvalue()))})
  
  yvalue = reactive({ equation(xvalue()) + noise() })
  
  bvalue = reactive({(sdtext(xvalue())^2/(2*sqrt(pi)*u2(xvalue())^2))^(2/5) })
  

  output$Plot1 <- renderPlot({
    x = xvalue()
    y = yvalue()
    b = bvalue()
    u = equation(x)
    ks = gaussian.smooth(x, y, b, input$win, input$proportion)
    
    plot(x,y, main= "Standard Deviation 100",pch = 20)
    lines(x, u, col = "blue")
    lines(x, ks, col = "red")  
    legend("top", legend = c("Underlying curve", "Optimal Curve"), col = c("blue", "red"), bty = "n", lty = 1)
    
  })

  output$Plot2 <- renderPlot({
    x = xvalue()
    y = yvalue()
    b = bvalue()
    u = equation(x)
    ks = gaussian.smooth(x, y, b, input$win, input$proportion)
    
    SSE = (gaussian.smooth(x,y,b,input$win, input$proportion)- u)^2     # remvoe the first and last 5 points
    MSE = mean(SSE, na.rm = T)  # remvoe the NA point (when x=0)
    
    
    bandw = 10^(seq(-8,8,0.5))
    MSE_b = NULL
    for (i in 1:length(bandw)) {
      SSE_vec  = (gaussian.smooth(x,y,rep(bandw[i], length(x)), input$win, input$proportion) - u)^2
      MSE_b[i] = mean(SSE_vec)
    }
    
    plot(seq(-8,8,0.5), MSE_b,pch = 20, ylab = "MSE", xlab = "bandwidth (10^x)", ylim = c(0, max(MSE_b)), xlim = c(-8,8), main = "MSE for different bandwidth value" )
    abline(h = MSE, col = "red") #MSE of optimal bandwidth
    legend("topleft", legend = c("Optimal bandwidth"), col = c("red"), lty = 1,  bty = "n")
    
  })
  
  
  
}

shinyApp(ui = ui, server = server)



```


